name: Build the project and deploy to GitHub Pages

# Runs the workflow on pushes and pull requests to the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow.

# Cancel in-progress runs when a new run is triggered on the same PR or branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Sets permissions of the `GITHUB_TOKEN` to allow deployment to GitHub Pages.
permissions:
  contents: read # Read access to repository contents.
  id-token: write # Required to upload the site to GitHub Pages.
  pages: write # Write access to GitHub Pages.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - name: Cache Nix store
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install github:cachix/devenv/v2.0.6
      - name: Build the project website within devenv
        run: devenv shell -- just build
      - name: Upload the site as a GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: website/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
